name: "L2TP/IPSec VPN Connect"
description: "Brings up a VPN (IPSec + L2TP) and exposes the PPP interface, then disconnects it at job end."
author: "Alexandre-Roussel48"
branding:
  icon: "lock"
  color: "blue"

inputs:
  vpn_gateway:
    required: true
  vpn_psk:
    required: true
  vpn_username:
    required: true
  vpn_password:
    required: true
  vpn_nt_domain:
    required: true
  vpn_ike:
    required: true
  vpn_esp:
    required: true

outputs:
  ppp_interface:
    description: "The detected VPN interface name"
  ppp_ip:
    description: "The VPN interface IP address"

runs:
  using: "node20"
  main: "dist/main/index.js"
  post: "dist/post/index.js"

