name: VPN Wrapper

on:
  workflow_call:
    inputs:
      vpn_gateway:
        required: true
        type: string
      vpn_psk:
        required: true
        type: string
      vpn_username:
        required: true
        type: string
      vpn_password:
        required: true
        type: string
      vpn_nt_domain:
        required: true
        type: string
      run_command:
        required: true
        type: string

jobs:
  vpn-wrapper:
    runs-on: ubuntu-latest

    steps:
      - name: Install Required Packages
        run: |
          sudo apt update
          sudo apt-get install -y strongswan xl2tpd net-tools dnsutils

      - name: Add VPN Configuration
        run: |
          sudo bash -c 'cat > /etc/ipsec.conf <<EOF
          conn myvpn
            auto=add
            keyexchange=ikev1
            authby=secret
            type=transport
            left=%defaultroute
            leftprotoport=17/1701
            rightprotoport=17/1701
            right=${{ inputs.vpn_gateway }}
            ike=3des-sha1-modp1024
            esp=3des-sha1
          EOF'

          sudo bash -c 'cat > /etc/ipsec.secrets <<EOF
          : PSK "${{ inputs.vpn_psk }}"
          EOF'

          sudo chmod 600 /etc/ipsec.secrets

          sudo bash -c 'cat > /etc/xl2tpd/xl2tpd.conf <<EOF
          [lac myvpn]
          lns = ${{ inputs.vpn_gateway }}
          ppp debug = yes
          pppoptfile = /etc/ppp/options.l2tpd.client
          length bit = yes
          EOF'

          sudo bash -c 'cat > /etc/ppp/options.l2tpd.client <<EOF
          ipcp-accept-local
          ipcp-accept-remote
          refuse-eap
          require-chap
          noccp
          noauth
          mtu 1280
          mru 1280
          noipdefault
          defaultroute
          usepeerdns
          connect-delay 5000
          domain "${{ inputs.vpn_nt_domain }}"
          name "${{ inputs.vpn_username }}"
          password "${{ inputs.vpn_password }}"
          EOF'

          sudo chmod 600 /etc/ppp/options.l2tpd.client

      - name: Start VPN
        run: |
          sudo mkdir -p /var/run/xl2tpd
          sudo touch /var/run/xl2tpd/l2tp-control
          sudo service ipsec restart
          sudo service xl2tpd restart
          sudo ipsec up myvpn
          echo "c myvpn" | sudo tee /var/run/xl2tpd/l2tp-control

          while ! ip addr show ppp0 | grep -q "inet "; do
              echo "Waiting for ppp0 to be up..."
              sleep 1
          done
          echo "ppp0 is up!"
          sudo ip route replace default dev ppp0
          echo "All traffic is now routed through VPN (ppp0)"

      - name: Run Caller Command
        run: |
          echo "🔹 Running caller command inside VPN..."
          eval "${{ inputs.run_command }}"

      - name: Disconnect VPN
        if: always()
        run: |
          echo "d myvpn" | sudo tee /var/run/xl2tpd/l2tp-control
          sudo ipsec down myvpn
          echo "VPN disconnected!"

